### ISSUE TITLE
Wrong world version?

### ISSUE THREAD

**Issue by AlxVillatoro** [RCP91/TibiaServer860#1]
I unzipped the world.rar file, but the world is not version 8.60.

**Comment by RCP91** [comment]
This custom client, also using map rme
https://drive.google.com/file/d/17ANun8UlgO0WBSj7RehS98xrMRZBSTLn/view?usp=sharing

**Comment by AlxVillatoro** [comment]
Thanks, I was able to open the world correctly, but is there a way so that the remers doesn't give me an error? I receive an unsupported client version, I have to import the map.

**Comment by RCP91** [comment]
Sometimes it's just a message, but the Open option can be loaded using this client's path.
